{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "topologyspread-webhook.rbacName" . }}
  labels:
  {{- include "topologyspread-webhook.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "topologyspread-webhook.rbacName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "topologyspread-webhook.serviceAccountName" . }}
{{- end }}
