apiVersion: v1
kind: Service
metadata:
  name: {{ include "topologyspread-webhook.serviceName" . }}
  labels:
    {{- include "topologyspread-webhook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9443
      protocol: TCP
      name: http
  selector:
    {{- include "topologyspread-webhook.selectorLabels" . | nindent 4 }}
